version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: nuno_postgres
    restart: always
    environment:
      POSTGRES_USER: nuno_user
      POSTGRES_PASSWORD: nuno_password
      POSTGRES_DB: nuno_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nuno_network

  redis:
    image: redis:7
    container_name: nuno_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nuno_network

networks:
  nuno_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
